### PR TITLE
Replace alert() with console.log() in the simple example

### PR DESCRIPTION
**Pull request by parambirs**

### CODE REVIEW

**Comment by mhegazy** [comment]
Not sure if alert is really bad here.. this is a simple inheritance toy example, and not intended to be used as a style guide.

**Comment by parambirs** [comment]
True. However, it only works in the browser. I had to tweak it when I was experimenting with the samples on node.js, so I thought I'll send in a PR. Feel free to decline if you think alert is better for most people.

**Comment by mhegazy** [comment]
this is a fair point. thanks.

**Comment by DanielRosenwasser** [comment]
Yup, I told @parambirs that this was a positive change on #64. Thanks

**Pull request merged**
