### PR TITLE
innerHTML-patch-for-firefox-40.0.2

### PR DESCRIPTION
**Pull request by tianyuanzhonglu**
see #33

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
It's weird that `innerText` isn't working - is there any reason for that?

**Comment by DanielRosenwasser** [comment]
Can we use `textContent` instead?

**Comment by tianyuanzhonglu** [comment]
`textContent` seems better, but I think `innerHtml` is more compatible for browsers.

[kangax](http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox)

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
