### PR TITLE
Added Anders //build demos with short explanation on how to run.

### PR DESCRIPTION
**Pull request by bowdenk7**
This is massive because we want to include all the dependencies needed to run the samples right after cloning.

### CODE REVIEW

**Comment by mhegazy** [comment]
should this be in a repo by itself, similar to https://github.com/Microsoft/ngconf2015demo

**Comment by ahejlsberg** [comment]
Agree with Mohamed, I think this should be in a separate repo.

**Comment by bowdenk7** [comment]
Makes sense, will do.

**Comment by bowdenk7** [comment]
https://github.com/Microsoft/typescript-build2016-demos

**Pull request closed without merging**
